### ISSUE TITLE
Error trying to install a local build

### ISSUE THREAD

**Issue by glennblock** [scriptcs-contrib/svm#20]
When trying to install a local version using I get an error message.

```
C:\Users\Glenn Block> svm install dev -f 'C:\src\scriptcs\src\ScriptCs\bin\Debug\'

 scriptcs version manager - 0.3.3

 Obtaining version 'dev' from 'C:\src\scriptcs\src\ScriptCs\bin\Debug\'.
 Installing version 'dev'.
The syntax of the command is incorrect.
 Version 'dev' is now available.
 Consider using svm use <version> to set it as the active scriptcs version.
```

**Comment by paulbouwer** [comment]
@glennblock - The paths during the `JUNCTION` creation (Windows softlink) were not escaped. The space in your svm home folder `C:\Users\Glenn Block\.svm` triggered the error.

The *nix version `ln -s` is correctly escaped and doesn't contain this bug. 

Fixed.

**Comment by glennblock** [comment]
Looks like this is in fact an issue. The problem was the "versions" directory was not created if you just installed SVM and then tried to mount a local version. Fix coming :-)
