### ISSUE TITLE
Move to scriptcs-contrib organization?

### ISSUE THREAD

**Issue by khellang** [scriptcs-contrib/svm#21]
Would you like to move this project over to the [scriptcs-contrib organization](https://github.com/scriptcs-contrib/)? You'll of course get pulled into the organization and keep push rights (own the project) :grin:

**Comment by glennblock** [comment]
Good timing. @paulbouwer and I talked about this last night. Agreed it should go to contrib!

**Comment by paulbouwer** [comment]
@glennblock @khellang Done :smile:

**Comment by khellang** [comment]
Yay! :grin::+1:
