### ISSUE TITLE
Allow installing a local version via symlink

### ISSUE THREAD

**Issue by glennblock** [scriptcs-contrib/svm#27]
Currently when you use the `-f` param, svm copies the folder into `.svm\versions`. It would be nice to have an option / or to make this actually create a symlink to the folder instead. This is in particularly useful when developing scriptcs itself as it means whenever you rebuild, svm will see the latest.

**Comment by paulbouwer** [comment]
This is already the behaviour. See *Install version from path* in the [Installing scriptcs versions](https://github.com/scriptcs-contrib/svm/wiki/Installing%20scriptcs%20versions) section of the wiki.

**Comment by glennblock** [comment]
I could swear when I used -f it ended up creating a copy. But I'll verify.
