### ISSUE TITLE
Install guide for Linux shows compiling Mono from source

### ISSUE THREAD

**Issue by akoeplinger** [scriptcs-contrib/svm#46]
See this [wiki page](https://github.com/scriptcs-contrib/svm/wiki/Installing%20svm%20on%20Linux). This is not the recommended way of installing Mono on Linux, there are .deb and .rpm distribution packages available for most systems, see http://www.mono-project.com/docs/getting-started/install/linux/

For Ubuntu 14.04 this boils down to:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update
sudo apt-get install mono-complete     # or mono-devel depending on what you need
```

**Comment by paulbouwer** [comment]
Thank you @akoeplinger. I think at the time I first started on `svm` and running `scriptcs` on linux, the mono releases for linux were a little behind those of OSX - it made more sense for me to compile from source and I just kept up with that process.

I'll update the wiki with your steps. Thanks again for keeping us up to date.
