### ISSUE TITLE
Show unsnapshotted source in svm list

### ISSUE THREAD

**Issue by adamralph** [scriptcs-contrib/svm#55]
E.g. if I install a version from a local source using

```batch
svm install 0.14.0 -f "C:\path\to\scriptcs\bin"
```

it would be **awesome** if

```batch
svm list
```

outputted

```
      0.12.0
      0.13.3
   *  0.14.0    C:\path\to\scriptcs\bin
```

**Comment by paulbouwer** [comment]
This has actually been on my mind this last week. I'll add it in the
upcoming release.

**Comment by adamralph** [comment]
Legend

**Comment by adamralph** [comment]
BTW - svm generally and `install -f` in particular is a true wonder. Streamlined in the last couple of days to no end.

**Comment by paulbouwer** [comment]
:)

**Comment by adamralph** [comment]
:+1: woot!
