### ISSUE TITLE
Create interim scriptcs release API

### ISSUE THREAD

**Issue by paulbouwer** [scriptcs-contrib/svm#61]
This is an interim measure to introduce a mechanism that allows for `svm` to reference new `scriptcs` releases (stable only - chocolatey) without requiring a new release of `svm`.

This feature will be implemented as a static file in this GitHub repo that `svm` can download and reference for an up to date list of `scriptcs` releases.

The long term goal is still to implement [#4 - Create svm web api](https://github.com/scriptcs-contrib/svm/issues/4).

**Comment by alfhenrik** [comment]
Why not just hit `https://api.github.com/repos/scriptcs/scriptcs/releases` and then extract versions from there?

**Comment by paulbouwer** [comment]
The api needs to contain download information for built releases (not just source) and have some additional smarts. I also wanted the eventual api to be decoupled from myget, nuget, chocolatey so that I could provide a stripped down, relevant and consolidated view across stable and nightly relelases.

The api was also going to manage `svm` release information etc.

This interim api is the firest step in the direction of not having to publish a release of `svm` just because there is a new release of `scriptcs`.

**Comment by alfhenrik** [comment]
:ok_hand:
