### ISSUE TITLE
Error shown during installation when PATH is null

### ISSUE THREAD

**Issue by adamralph** [scriptcs-contrib/svm#76]
I just installed svm on a fresh Windows 10 box, and I got the following:

![image](https://cloud.githubusercontent.com/assets/677704/10124129/60d83b88-654d-11e5-9c15-2385be9382d1.png)

I'm guessing that my *user* PATH was `null` before the installation. After installation it is:

![image](https://cloud.githubusercontent.com/assets/677704/10124139/a2fe3a4e-654d-11e5-85fe-cc8417111d45.png)

Everything seems to work OK, and I'm guessing there is no net bad effect, but the error message is quite disconcerting.

**Comment by paulbouwer** [comment]
Thanks for finding @adamralph - that should have been more defensively coded :disappointed:
