### ISSUE TITLE
Multiple installs from path show the same path

### ISSUE THREAD

**Issue by ryanrousseau** [scriptcs-contrib/svm#77]
I noticed today that if I have two installs from different paths, svm list will show the same path for all of them. It looks like just a display issue as using each one will use the correct version.

In this screenshot, I have dev and dev-latest which are actually the same path, so this is correct.

![image](https://cloud.githubusercontent.com/assets/1571799/10747316/bc287ecc-7c21-11e5-986f-8c4e3ae51520.png)

If I install from the current directory and then list again, all three will show the new path (notice the /gb/ in each one)

![image](https://cloud.githubusercontent.com/assets/1571799/10747337/f0a5c024-7c21-11e5-8cd5-97baee191b6e.png)

Removing the new install will revert the other paths

![image](https://cloud.githubusercontent.com/assets/1571799/10747350/1a983af6-7c22-11e5-8c42-bd2d41a01841.png)

I can take a look at it later this week, but wanted to go ahead and report it.

**Comment by paulbouwer** [comment]
Thanks for reporting @ryanrousseau

**Comment by ryanrousseau** [comment]
Hey @paulbouwer, I've got a fix for this but I'm not sure if I should send the PR to dev or master. Let me know and I'll send it.

Thanks!

**Comment by paulbouwer** [comment]
Awesome! Send it to master for now - there are other fixes in here waiting
for release. Need to get dev branch process going :)

Thanks for the PR!
